#!/bin/bash


mkdir -p output
cd ../GraMi

echo "graphs-combined-err-0.0-grami-dist-3-supp-100"
./grami "-f" '../graphs/graphs-combined-err-0.0-grami' '-s' "100" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.0-grami-dist-3-supp-100"
echo "graphs-combined-err-0.0-grami-dist-3-supp-90"
./grami "-f" '../graphs/graphs-combined-err-0.0-grami' '-s' "90" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.0-grami-dist-3-supp-90"
echo "graphs-combined-err-0.0-grami-dist-3-supp-80"
./grami "-f" '../graphs/graphs-combined-err-0.0-grami' '-s' "80" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.0-grami-dist-3-supp-80"
echo "graphs-combined-err-0.0-grami-dist-3-supp-70"
./grami "-f" '../graphs/graphs-combined-err-0.0-grami' '-s' "70" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.0-grami-dist-3-supp-70"
echo "graphs-combined-err-0.0-grami-dist-3-supp-60"
./grami "-f" '../graphs/graphs-combined-err-0.0-grami' '-s' "60" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.0-grami-dist-3-supp-60"
echo "graphs-combined-err-0.0-grami-dist-3-supp-50"
./grami "-f" '../graphs/graphs-combined-err-0.0-grami' '-s' "50" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.0-grami-dist-3-supp-50"

echo "graphs-combined-err-0.01-grami-dist-3-supp-100"
./grami "-f" '../graphs/graphs-combined-err-0.01-grami' '-s' "100" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.01-grami-dist-3-supp-100"
echo "graphs-combined-err-0.01-grami-dist-3-supp-90"
./grami "-f" '../graphs/graphs-combined-err-0.01-grami' '-s' "90" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.01-grami-dist-3-supp-90"
echo "graphs-combined-err-0.01-grami-dist-3-supp-80"
./grami "-f" '../graphs/graphs-combined-err-0.01-grami' '-s' "80" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.01-grami-dist-3-supp-80"
echo "graphs-combined-err-0.01-grami-dist-3-supp-70"
./grami "-f" '../graphs/graphs-combined-err-0.01-grami' '-s' "70" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.01-grami-dist-3-supp-70"
echo "graphs-combined-err-0.01-grami-dist-3-supp-60"
./grami "-f" '../graphs/graphs-combined-err-0.01-grami' '-s' "60" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.01-grami-dist-3-supp-60"
echo "graphs-combined-err-0.01-grami-dist-3-supp-50"
./grami "-f" '../graphs/graphs-combined-err-0.01-grami' '-s' "50" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.01-grami-dist-3-supp-50"

echo "graphs-combined-err-0.04-grami-dist-3-supp-100"
./grami "-f" '../graphs/graphs-combined-err-0.04-grami' '-s' "100" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.04-grami-dist-3-supp-100"
echo "graphs-combined-err-0.04-grami-dist-3-supp-90"
./grami "-f" '../graphs/graphs-combined-err-0.04-grami' '-s' "90" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.04-grami-dist-3-supp-90"
echo "graphs-combined-err-0.04-grami-dist-3-supp-80"
./grami "-f" '../graphs/graphs-combined-err-0.04-grami' '-s' "80" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.04-grami-dist-3-supp-80"
echo "graphs-combined-err-0.04-grami-dist-3-supp-70"
./grami "-f" '../graphs/graphs-combined-err-0.04-grami' '-s' "70" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.04-grami-dist-3-supp-70"
echo "graphs-combined-err-0.04-grami-dist-3-supp-60"
./grami "-f" '../graphs/graphs-combined-err-0.04-grami' '-s' "60" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.04-grami-dist-3-supp-60"
echo "graphs-combined-err-0.04-grami-dist-3-supp-50"
./grami "-f" '../graphs/graphs-combined-err-0.04-grami' '-s' "50" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.04-grami-dist-3-supp-50"

echo "graphs-combined-err-0.05-grami-dist-3-supp-100"
./grami "-f" '../graphs/graphs-combined-err-0.05-grami' '-s' "100" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.05-grami-dist-3-supp-100"
echo "graphs-combined-err-0.05-grami-dist-3-supp-90"
./grami "-f" '../graphs/graphs-combined-err-0.05-grami' '-s' "90" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.05-grami-dist-3-supp-90"
echo "graphs-combined-err-0.05-grami-dist-3-supp-80"
./grami "-f" '../graphs/graphs-combined-err-0.05-grami' '-s' "80" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.05-grami-dist-3-supp-80"
echo "graphs-combined-err-0.05-grami-dist-3-supp-70"
./grami "-f" '../graphs/graphs-combined-err-0.05-grami' '-s' "70" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.05-grami-dist-3-supp-70"
echo "graphs-combined-err-0.05-grami-dist-3-supp-60"
./grami "-f" '../graphs/graphs-combined-err-0.05-grami' '-s' "60" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.05-grami-dist-3-supp-60"
echo "graphs-combined-err-0.05-grami-dist-3-supp-50"
./grami "-f" '../graphs/graphs-combined-err-0.05-grami' '-s' "50" "-t" "1" "-p" "1" "-d" "3" "-approxA" "0.0002" > /dev/null && mv "Output.txt" "../output/graphs-combined-err-0.05-grami-dist-3-supp-50"